package com.aegisnav.app.worker

import android.content.Context
import androidx.datastore.preferences.core.stringPreferencesKey
import com.aegisnav.app.security.SecureDataStore
import com.aegisnav.app.security.editBlocking
import kotlinx.coroutines.flow.first
import com.aegisnav.app.util.AppLog
import androidx.hilt.work.HiltWorker
import androidx.work.*
import com.google.gson.stream.JsonReader
import com.aegisnav.app.data.dao.RedLightCameraDao
import com.aegisnav.app.data.model.RedLightCamera
import dagger.assisted.Assisted
import dagger.assisted.AssistedInject
import java.util.concurrent.TimeUnit

/**
 * Weekly WorkManager task that re-imports the bundled red light camera dataset.
 * Reads us_redlight_cameras.geojson from assets, upserts into Room.
 * Idempotent — safe to run multiple times. Skips if asset is unchanged.
 * Asset is generated by tools/sync_surveillance_data.py at build time.
 */
@HiltWorker
class RedLightDataSyncWorker @AssistedInject constructor(
    @Assisted private val appContext: Context,
    @Assisted workerParams: WorkerParameters,
    private val redLightCameraDao: RedLightCameraDao
) : CoroutineWorker(appContext, workerParams) {

    companion object {
        const val WORK_NAME = "redlight_data_sync_weekly"
        private const val TAG = "RedLightDataSyncWorker"
        private const val ASSET_NAME = "us_redlight_cameras.geojson"

        fun buildPeriodicRequest(): PeriodicWorkRequest =
            PeriodicWorkRequestBuilder<RedLightDataSyncWorker>(7, TimeUnit.DAYS)
                .setConstraints(
                    Constraints.Builder()
                        .setRequiredNetworkType(NetworkType.NOT_REQUIRED)
                        .build()
                )
                .setBackoffCriteria(BackoffPolicy.EXPONENTIAL, 30, TimeUnit.MINUTES)
                .addTag(WORK_NAME)
                .build()
    }

    override suspend fun doWork(): Result {
        AppLog.i(TAG, "RedLightDataSyncWorker started")

        val dataStore = SecureDataStore.get(applicationContext, "redlight_prefs")
        val checksumKey = stringPreferencesKey("redlight_asset_checksum_v1")
        val storedChecksum  = dataStore.data.first()[checksumKey] ?: ""
        val currentChecksum = getAssetChecksum(applicationContext, ASSET_NAME)
        if (currentChecksum.isNotEmpty() && currentChecksum == storedChecksum) {
            AppLog.i(TAG, "Red light asset unchanged — skipping reimport")
            return Result.success()
        }

        return try {
            val count = upsertBundledAsset()
            AppLog.i(TAG, "Red light sync complete: $count cameras upserted")
            dataStore.editBlocking { this[checksumKey] = currentChecksum }
            Result.success(workDataOf("cameras_synced" to count))
        } catch (e: java.io.IOException) {
            AppLog.e(TAG, "Transient error, retrying: ${e.message}")
            Result.retry()
        } catch (e: Exception) {
            AppLog.e(TAG, "Permanent error: ${e.message}")
            Result.failure()
        }
    }

    private fun getAssetChecksum(context: Context, assetName: String): String {
        return try {
            val md = java.security.MessageDigest.getInstance("SHA-256")
            context.assets.open(assetName).use { input ->
                val buf = ByteArray(8192); var n: Int
                while (input.read(buf).also { n = it } != -1) md.update(buf, 0, n)
            }
            md.digest().joinToString("") { "%02x".format(it) }
        } catch (e: Exception) { "" }
    }

    private suspend fun upsertBundledAsset(): Int {
        try {
            appContext.assets.open(ASSET_NAME)
        } catch (e: Exception) {
            AppLog.w(TAG, "$ASSET_NAME not found in assets — run tools/sync_surveillance_data.py first")
            return 0
        }

        var count = 0
        appContext.assets.open(ASSET_NAME).bufferedReader().use { reader ->
            val jr = JsonReader(reader)
            jr.beginObject()
            while (jr.hasNext()) {
                if (jr.nextName() == "features") {
                    jr.beginArray()
                    while (jr.hasNext()) {
                        parseFeature(jr)?.let { cam ->
                            redLightCameraDao.upsert(cam)
                            count++
                        }
                    }
                    jr.endArray()
                } else {
                    jr.skipValue()
                }
            }
            jr.endObject()
        }
        return count
    }

    private fun parseFeature(jr: JsonReader): RedLightCamera? {
        var lat = Double.NaN; var lon = Double.NaN
        var desc = "Red Light Camera"; var source = "OSM"; var state = ""
        jr.beginObject()
        while (jr.hasNext()) {
            when (jr.nextName()) {
                "geometry" -> {
                    jr.beginObject()
                    while (jr.hasNext()) {
                        if (jr.nextName() == "coordinates") {
                            jr.beginArray()
                            if (jr.hasNext()) lon = jr.nextDouble()
                            if (jr.hasNext()) lat = jr.nextDouble()
                            while (jr.hasNext()) jr.skipValue()
                            jr.endArray()
                        } else jr.skipValue()
                    }
                    jr.endObject()
                }
                "properties" -> {
                    jr.beginObject()
                    while (jr.hasNext()) {
                        when (jr.nextName()) {
                            "desc", "name", "description" -> desc = jr.nextString()
                            "source"                      -> source = jr.nextString()
                            "state"                       -> state = jr.nextString()
                            else                          -> jr.skipValue()
                        }
                    }
                    jr.endObject()
                }
                else -> jr.skipValue()
            }
        }
        jr.endObject()
        return if (!lat.isNaN() && !lon.isNaN())
            RedLightCamera(lat = lat, lon = lon, desc = desc, source = source, state = state)
        else null
    }
}
